filebeat.inputs:
  - type: filestream
    id: docker-logs
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'

    parsers:
      - container:
          stream: all
          format: auto

    include:
      - "api-gateway"
      - "service-a"
      - "service-b"
      - "service-c"

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "qwerty123456"
  timeout: 60s

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
logging.to_stderr: true
