server {
    listen 80;
    
    # Прокси для сервисов
    location /api/a {
        proxy_pass http://service-a:80/;
    }
    
    location /api/b {
        proxy_pass http://service-b:80/;
    }
    
    location /api/c {
        proxy_pass http://service-c:80/;
    }
    
    # Проверка здоровья
    location / {
        return 200 'API Gateway OK\n';
        add_header Content-Type text/plain;
    }
}
